#!/usr/bin/env bats
load helpers

# Declare the service
consul_service="consul"
address="$(dig +short ${consul_service})"
port="8500"
service="php"

@test "Check the global configuration is registered" {

  value="$(cat << EOF
[global]
include=etc/php-fpm.d/*.conf
EOF
)"

  php_conf_template="/etc/consul-template/templates/php.conf.ctmpl"
  php_conf_file="/usr/local/etc/php-fpm.conf"

  # Remove the default configuration
  status=$(rm -f ${php_conf_file};echo $?)
  [ "$status" -eq 0 ]

  # Register the file
  run register_key "service/${service}/php-fpm.conf" "${value}"
  [ "$status" -eq 0 ]

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template ${php_conf_template}:${php_conf_file} -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f ${php_conf_file};echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the content
  status=$(grep "[global]" ${php_conf_file} 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]

  # Check the config is valid
  status=$(php-fpm --test 2> /dev/null;echo $?)
  [ "$status" -eq 0 ]
}

@test "Check the php.ini configuration is registered" {

  value="$(cat << EOF
date.timezone='America/New_York'
EOF
)"

  php_ini_template="/etc/consul-template/templates/php.ini.ctmpl"
  php_ini_file="/usr/local/etc/php/php.ini"

  # Remove the default configuration
  status=$(rm -f ${php_ini_file};echo $?)
  [ "$status" -eq 0 ]

  # Register the file
  run register_key "service/${service}/php.ini" "${value}"
  [ "$status" -eq 0 ]

  # Call consul template to generate the configuration
  status=$(consul-template -consul-addr ${consul_service}:8500 -template ${php_ini_template}:${php_ini_file} -once;echo $?)
  [ "$status" -eq 0 ]

  # Check the expected configuration has been generated by consul-template
  status=$(test -f ${php_ini_file};echo $?)
  [ "$status" -eq 0 ]

  # Check we can find the content
  status=$(grep "date.timezone" ${php_ini_file} 2>&1 > /dev/null;echo $?)
  [ "$status" -eq 0 ]

}


